import uuid
import enum
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import (
    String, DateTime, Enum as SQLEnum, ForeignKey, Index,
    Numeric, Text, UniqueConstraint, CheckConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID, JSON

from app.core.database import Base


class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class PaymentMethod(str, enum.Enum):
    MOBILE_MONEY = "MOBILE_MONEY"
    BANK_CARD = "BANK_CARD"


class Payment(Base):
    __tablename__ = "payment_gateway_payments"
    __table_args__ = (
        UniqueConstraint("reference", name="uq_pgp_reference"),
        UniqueConstraint("payment_token", name="uq_pgp_payment_token"),
        UniqueConstraint("webhook_reference", name="uq_pgp_webhook_reference"),
        Index("ix_pgp_merchant_created", "merchant_id", "created_at"),
        Index("ix_pgp_status", "status"),
        Index("ix_pgp_reference", "reference"),
        Index("ix_pgp_payment_token", "payment_token"),
        CheckConstraint("amount > 0", name="ck_pgp_amount_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    merchant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("payment_merchants.id", ondelete="RESTRICT"),
        index=True, nullable=False,
    )

    # Payment token (unique, used to identify payment in checkout flow)
    payment_token: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False
    )

    # Payment reference (unique per payment, generated by the gateway)
    reference: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)

    # Merchant-provided order reference
    merchant_reference: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)

    # Amount and currency
    amount: Mapped[Decimal] = mapped_column(
        Numeric(precision=12, scale=2), nullable=False
    )
    fee: Mapped[Decimal] = mapped_column(
        Numeric(precision=10, scale=2), default=Decimal("0"), server_default="0", nullable=False
    )
    currency: Mapped[str] = mapped_column(String(3), default="XAF", nullable=False)

    # Payment details
    method: Mapped[PaymentMethod | None] = mapped_column(
        SQLEnum(PaymentMethod), nullable=True
    )
    status: Mapped[PaymentStatus] = mapped_column(
        SQLEnum(PaymentStatus), default=PaymentStatus.PENDING, nullable=False
    )

    # Customer info (JSON: {name, email, phone})
    customer_info: Mapped[dict | None] = mapped_column("customer_info", JSON, nullable=True)

    # Description
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Callback URLs
    callback_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    return_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # TouchPay data (JSON: provider response data, transaction IDs, etc.)
    touchpay_data: Mapped[dict | None] = mapped_column("touchpay_data", JSON, nullable=True)

    # Provider tracking
    provider_transaction_id: Mapped[str | None] = mapped_column(
        String(255), nullable=True, index=True
    )
    webhook_reference: Mapped[str | None] = mapped_column(
        String(255), nullable=True, default=None, index=True
    )

    # Metadata (flexible JSON storage from merchant)
    payment_metadata: Mapped[dict | None] = mapped_column("metadata", JSON, nullable=True)

    # Payment link URL (for redirect-based payments)
    payment_url: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    # Timestamps
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationships
    merchant: Mapped["Merchant"] = relationship("Merchant", back_populates="payments")

    # Convenience properties to access customer_info fields
    @property
    def customer_name(self) -> str | None:
        return (self.customer_info or {}).get("name")

    @property
    def customer_email(self) -> str | None:
        return (self.customer_info or {}).get("email")

    @property
    def customer_phone(self) -> str | None:
        return (self.customer_info or {}).get("phone")

    def __repr__(self):
        return f"<Payment {self.reference} {self.amount} {self.currency} [{self.status}]>"
