"""
AccountPE (Swychr) webhook receiver.

Two delivery paths land here:
  1. Account-level webhook ("payment_link_status_updated"), signed with
     HMAC-SHA256 over "{timestamp}.{raw_body}" (X-Webhook-Timestamp /
     X-Webhook-Signature headers). This is the trusted channel.
  2. Per-request callback_url / failed_callback_url set at initiation.
     Those deliveries are unsigned, so they are only accepted when the
     ?token= query parameter matches the payment's payment_token (the URL
     containing the token was generated by us and shared only with
     AccountPE at initiation).

Status codes (data.data.attributes.status):
  0 PENDING, 1 SUCCESSFUL, 2 FAILED, 3 EXPIRED, 4 PROCESSING,
  5 DECLINED, 6 REJECTED
"""
import asyncio
import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.payment import Payment, PaymentStatus
from app.services.accountpe_service import (
    STATUS_EXPIRED, STATUS_FAILED, STATUS_PENDING, STATUS_SUCCESS,
    verify_webhook_signature,
)
from app.services.provider_service import provider_service

logger = logging.getLogger(__name__)

router = APIRouter()

_STATUS_LABELS = {
    0: "PENDING", 1: "SUCCESSFUL", 2: "FAILED", 3: "EXPIRED",
    4: "PROCESSING", 5: "DECLINED", 6: "REJECTED",
}

_TERMINAL = (PaymentStatus.COMPLETED, PaymentStatus.FAILED, PaymentStatus.CANCELLED)


def _extract_attributes(payload: dict) -> dict:
    """Locate the attribute dict across AccountPE payload shapes."""
    data = payload.get("data") or {}
    inner = data.get("data") or data
    attrs = inner.get("attributes") if isinstance(inner, dict) else None
    if isinstance(attrs, dict):
        return attrs
    if isinstance(inner, dict) and "transaction_id" in inner:
        return inner
    if "transaction_id" in payload:
        return payload
    return {}


@router.post("/accountpe")
async def accountpe_webhook(
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    raw_body = await request.body()
    # Per-request callbacks don't follow the documented account-webhook
    # payload — be tolerant: JSON, form-encoded, or empty body.
    payload: dict = {}
    if raw_body:
        try:
            data = await request.json()
            if isinstance(data, dict):
                payload = data
        except Exception:
            try:
                payload = dict(await request.form())
            except Exception:
                payload = {}

    attrs = _extract_attributes(payload)
    transaction_id = attrs.get("transaction_id")
    token = request.query_params.get("token")

    payment = None
    if transaction_id:
        result = await db.execute(select(Payment).where(Payment.reference == transaction_id))
        payment = result.scalar_one_or_none()
    if payment is None and token:
        # Callback identified only by our per-payment token in the URL
        result = await db.execute(select(Payment).where(Payment.payment_token == token))
        payment = result.scalar_one_or_none()
        if payment is not None:
            transaction_id = payment.reference

    if not payment:
        logger.warning(
            "AccountPE webhook: payment not found (transaction_id=%s) body=%s",
            transaction_id, raw_body[:500],
        )
        raise HTTPException(status_code=404, detail="Payment not found")

    # --- Authenticate the delivery ---
    timestamp = request.headers.get("X-Webhook-Timestamp")
    signature = request.headers.get("X-Webhook-Signature")
    authenticated = False

    if timestamp and signature:
        provider = await provider_service.get_provider(db, "ACCOUNTPE")
        secret = ""
        if provider:
            secret = provider_service.decrypted_config(provider).get("webhook_secret") or ""
        authenticated = verify_webhook_signature(raw_body, timestamp, signature, secret)
        if not authenticated:
            logger.warning("AccountPE webhook: invalid signature for %s", transaction_id)

    if not authenticated:
        authenticated = bool(token) and token == payment.payment_token

    if not authenticated:
        raise HTTPException(status_code=401, detail="Invalid webhook signature")

    # --- Map status ---
    # Prefer the payload status (account-level webhook). Per-request
    # callbacks may carry no status at all: fall back to the outcome query
    # param we bake into the two callback URLs at initiation
    # (outcome=success on callback_url, outcome=failed on failed_callback_url).
    raw_status = attrs.get("status")
    if raw_status is None:
        outcome = (request.query_params.get("outcome") or "").lower()
        if outcome == "success":
            raw_status = 1
        elif outcome == "failed":
            raw_status = 2
        else:
            logger.warning(
                "AccountPE webhook: no status for %s (outcome=%r) body=%s",
                transaction_id, outcome, raw_body[:500],
            )
            raise HTTPException(status_code=400, detail="Missing or invalid status")
    try:
        provider_status = int(raw_status)
    except (TypeError, ValueError):
        # e.g. the payin creation response uses string statuses ("pending")
        label_to_code = {v.lower(): k for k, v in _STATUS_LABELS.items()}
        provider_status = label_to_code.get(str(raw_status).lower())
        if provider_status is None:
            raise HTTPException(status_code=400, detail="Missing or invalid status")

    status_label = _STATUS_LABELS.get(provider_status, str(provider_status))

    if provider_status in STATUS_SUCCESS:
        new_status = PaymentStatus.COMPLETED
    elif provider_status in STATUS_FAILED:
        new_status = PaymentStatus.FAILED
    elif provider_status in STATUS_EXPIRED:
        new_status = PaymentStatus.EXPIRED
    elif provider_status in STATUS_PENDING:
        new_status = PaymentStatus.PROCESSING
    else:
        logger.warning(
            "AccountPE webhook: unknown status %s for %s", provider_status, transaction_id,
        )
        return {"status": "ok", "message": f"Ignored unknown status {provider_status}"}

    # --- Idempotency ---
    if payment.status in _TERMINAL:
        logger.info(
            "AccountPE webhook: payment %s already %s, skipping",
            payment.reference, payment.status.value,
        )
        return {"status": "ok", "message": "Already processed"}

    if new_status == PaymentStatus.PROCESSING and payment.status != PaymentStatus.PENDING:
        return {"status": "ok", "message": "No transition"}

    old_status = payment.status
    merged = dict(payment.touchpay_data or {})
    merged.update({
        "provider": "ACCOUNTPE",
        "accountpe_status": provider_status,
        "message": f"AccountPE: {status_label.lower()}",
        "accountpe_payload": attrs,
    })
    update_values: dict = {"status": new_status, "touchpay_data": merged}
    if attrs.get("id") is not None:
        update_values["provider_transaction_id"] = str(attrs["id"])
    if new_status == PaymentStatus.COMPLETED:
        update_values["completed_at"] = datetime.now(timezone.utc)

    result = await db.execute(
        update(Payment)
        .where(Payment.id == payment.id, Payment.status == old_status)
        .values(**update_values)
        .returning(Payment.id)
    )
    if result.first() is None:
        logger.info("AccountPE webhook: concurrent update for %s", payment.reference)
        return {"status": "ok", "message": "Concurrent update"}
    await db.commit()

    logger.info(
        "AccountPE webhook: payment %s updated %s -> %s (provider status %s)",
        payment.reference, old_status.value, new_status.value, status_label,
    )

    if new_status in _TERMINAL or new_status == PaymentStatus.EXPIRED:
        try:
            from app.services.notification import notify_merchant
            asyncio.create_task(notify_merchant(str(payment.id)))
        except Exception as exc:
            logger.warning("Failed to trigger merchant notification: %s", exc)

    return {"status": "ok", "reference": payment.reference, "new_status": new_status.value}
